In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
#Creating a two dimensional array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#create an arrays of zeros
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#create an array of ones
d=np.ones((2,2))
print(d)

[[1. 1.]
 [1. 1.]]


In [9]:
#Adding two arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [10]:
#Multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

[[ 5 12]
 [21 32]]


In [11]:
#Performing matrix multiplication
g=np.array([[1,2],[3,4]])
h=np.array([[5,6],[7,8]])
i=np.dot(g,h)
print(i)

[[19 22]
 [43 50]]
