<a href="https://colab.research.google.com/github/pramanand-coder/Python-programming/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
import numpy as np

In [2]:
iris=load_iris()

In [3]:
iris.data.shape

(150, 4)

In [4]:
x=iris.data
y=iris.target

In [5]:
np.unique(y)

array([0, 1, 2])

In [6]:
y.shape

(150,)

In [7]:
print(y[50])

1


In [8]:
print(x[50,:])

[7.  3.2 4.7 1.4]


spliting data into train and test data

In [9]:
def trainTest(X,Y,test_size):
  idx=np.random.permutation(y.size)
  ts=int(np.floor(test_size*y.size))
  testIdx=idx[:ts]
  trainIdx=idx[ts:]
  xtrain=x[trainIdx,:]
  xtest=x[testIdx,:]
  ytrain=y[trainIdx]
  ytest=y[testIdx]
  return xtrain,xtest,ytrain,ytest
x_train,x_test,y_train,y_test=trainTest(x,y,0.25)

In [10]:
print(x_train.shape,x_test.shape)

(113, 4) (37, 4)


In [11]:
print(y_train.shape,y_test.shape)

(113,) (37,)


In [12]:
D=np.sum((x_train[:,np.newaxis,:]-x_test[np.newaxis,:,:])**2,axis=2)

In [13]:
D.shape

(113, 37)

In [14]:
D[0,0]

0.27000000000000024

In [15]:
nidx=np.argsort(D,axis=0)
print(nidx)
print(nidx.shape)

[[102  51 103 ...  21 104   3]
 [ 70  85  51 ...  51   2  10]
 [111  76  39 ...  30  46  22]
 ...
 [ 38  34  34 ...  34 101  38]
 [ 68   1   1 ...   1  68  90]
 [ 90  27  27 ...  27  90  68]]
(113, 37)


In [16]:
nidx[:5,0]

array([102,  70, 111,   0,  46])

In [17]:
idx=nidx[:10,1]

In [18]:
from scipy import stats
stats.mode(y_train[idx])

ModeResult(mode=0, count=10)

In [19]:
y_test[1]

0

numpy towards pandas

In [20]:
x=np.array([("Pramanand","DUV100",100),("JYOTI","NUR100",98)],
           dtype=[('Name','U10'),("ID","U8"),('Mark','i8')])

In [21]:
print(x)

[('Pramanand', 'DUV100', 100) ('JYOTI', 'NUR100',  98)]


In [22]:
x['Name']

array(['Pramanand', 'JYOTI'], dtype='<U10')

In [23]:
x[["Name","Mark"]]

array([('Pramanand', 100), ('JYOTI',  98)],
      dtype={'names': ['Name', 'Mark'], 'formats': ['<U10', '<i8'], 'offsets': [0, 72], 'itemsize': 80})